spring:
  profiles:
    active: local
    group:
      local: local, common
      prod: prod, common

  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath*:sql/MEMBER.sql
      mode: always