spring:
  application:
    name: stuti

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true
    hibernate:
      naming:
        physical-strategy: prgrms.project.stuti.global.config.SnakeUpperCaseNamingStrategy
        
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 1MB

  security:
    # URI ignore or permit-all
    patterns:
      permitAll: [ ]
      member:
        GET: [ ]
        POST: [ ]
        PATCH: [ ]
        PUT: [ ]
        DELETE: [ ]
    # Security OAuth
    oauth2:
      client:
        registration:
          naver:
            client-id: ZJzO1vImgGzN2XHQZ__F
            client-secret: mxnBPNlucz
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: [ name, email, profile_image ]
          google:
            client-id: 941480679229-7seu3agto0jlhnuq0hv6v4vj11eoqf5r.apps.googleusercontent.com
            client-secret: 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
            scope: [ profile, email ]
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

app:
  jwt:
    header: token
    issuer: prgrms
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 3000000000
    refreshTokenExpiry: 7776000000
  # cors
  cors:
    allowed-methods: GET,POST,PUT,PATCH,DELETE
    allowed-headers: '*'
    max-age: 3600
  # OAuth path
  oauth:
    signupPath: "/signup"
    signupTime: 300000
    loginSuccessPath: "/main"

